version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: andrei
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build: .
    image: flask-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # Set this to the service name 'db' as defined below
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: andrei
      DATABASE_NAME: flaskdb

volumes:
  mysql_data:
