---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          # image: mysql-db:latest
          image: andreisarandan900/flask-web-application:mysql-db
          ports:
            - containerPort: 3306
          # The MySQL Dockerfile already sets the environment variables for the root user and database,
          # but you can include them here if you want to override or confirm.
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "andrei"
            - name: MYSQL_DATABASE
              value: "flaskdb"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          # image: flask-app:latest
          image: andreisarandan900/flask-web-application:flask-app
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "mysql-service" # Uses the MySQL service name for DNS resolution
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "andrei"
            - name: DATABASE_NAME
              value: "flaskdb"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
