"""Add Registration class + germany and france

Revision ID: 7e31d5a8a7a8
Revises: 4573c03ad588
Create Date: 2024-03-17 18:32:40.722551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e31d5a8a7a8'
down_revision = '4573c03ad588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'car', ['car_id'], ['id'])
        batch_op.drop_column('country')

    # ### end Alembic commands ###
