"""Initial migration.

Revision ID: 023609fa480e
Revises: 
Create Date: 2024-02-13 17:46:14.330304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023609fa480e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_class', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('minimum_diesel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minimum_petrol', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fines', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('registration_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('registration_validity', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('required_registration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exception_country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('required_pass')
        batch_op.drop_column('descriptions')
        batch_op.drop_column('minimum_euro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_euro', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('descriptions', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('required_pass', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('exception_country')
        batch_op.drop_column('required_registration')
        batch_op.drop_column('registration_validity')
        batch_op.drop_column('registration_type')
        batch_op.drop_column('fines')
        batch_op.drop_column('minimum_petrol')
        batch_op.drop_column('minimum_diesel')
        batch_op.drop_column('registration_class')

    # ### end Alembic commands ###
