"""Add Total Bans column to Blocked User table

Revision ID: 179f8a81fb54
Revises: 31d2a7387e99
Create Date: 2025-01-05 12:03:56.382785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179f8a81fb54'
down_revision = '31d2a7387e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blocked_Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_bans', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blocked_Users', schema=None) as batch_op:
        batch_op.drop_column('total_bans')

    # ### end Alembic commands ###
