"""Rename Blocked_Users and Requests_Log

Revision ID: 31d2a7387e99
Revises: 946df4a8239c
Create Date: 2025-01-04 18:06:32.469389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d2a7387e99'
down_revision = '946df4a8239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Requests Log')
    op.drop_table('Blocked Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blocked Users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('blocked_until', sa.DATETIME(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Requests Log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('endpoint', sa.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
