"""Add ip column in Blocked Users table (second try)

Revision ID: 4813823040bb
Revises: 6f58e932db76
Create Date: 2025-01-04 16:58:37.827853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4813823040bb'
down_revision = '6f58e932db76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blocked Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blocked Users', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
