"""Add IP column to Request Log table

Revision ID: 66ffef9b1d9d
Revises: 4813823040bb
Create Date: 2025-01-04 17:45:11.039561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ffef9b1d9d'
down_revision = '4813823040bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Requests Log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Requests Log', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
