"""Make BlockedUser.ip_address primay key and RequestLog.user_id nullable

Revision ID: 946df4a8239c
Revises: 66ffef9b1d9d
Create Date: 2025-01-04 17:49:14.840641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946df4a8239c'
down_revision = '66ffef9b1d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blocked Users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('Requests Log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Requests Log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Blocked Users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
