# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flask server CI pipeline

on:
  push:
    branches: [ "main", "containerize-application" ]
  pull_request:
    branches: [ "main", "containerize-application" ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create secrets.json
        run: echo "${{ secrets.SECRETS_JSON }}" > secrets.json
      
      - name: Build Docker image
        run: docker build -t flask-server:latest .

      - name: Run Container
        run: docker run -d -p 5000:5000 --name=flask-server flask-server:latest

      - name: Get Docker Containers
        run: docker ps -a

      - name: Get Flask Server Logs
        run: docker logs flask-server

      - name: Wait for Container Startup
        run: sleep 10

      - name: Check MySQL Connection
        run: docker exec -i flask-server mysqladmin -h host.docker.internal -u root -pandrei ping
        
      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --disable-warnings -q
